version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 3
    groups:
      npm-patch-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-security-patch-minor:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
      include: scope

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 3
    groups:
      pip-patch-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      pip-security-patch-minor:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 3
    groups:
      github-actions-patch-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(ci)
      include: scope
